---
Name: galactic
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: themes
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Galactic\SiteConfigExtension
SilverStripe\Assets\File:
  extensions:
    - Galactic\UploadFileExtension
SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - Galactic\UploadFileFactoryExtension
